/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_mjahn_agent_inspector_VMInspector */

#ifndef _Included_net_mjahn_agent_inspector_VMInspector
#define _Included_net_mjahn_agent_inspector_VMInspector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_mjahn_agent_inspector_VMInspector
 * Method:    getSizeOfAllLoadedObjectsBy
 * Signature: (Ljava/lang/ClassLoader;)J
 */
JNIEXPORT jlong JNICALL Java_net_mjahn_agent_inspector_VMInspector_getSizeOfAllLoadedObjectsBy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_mjahn_agent_inspector_VMInspector
 * Method:    getAllLoadedObjectsOf
 * Signature: (Ljava/lang/ClassLoader;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_net_mjahn_agent_inspector_VMInspector_getAllLoadedObjectsOf
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_mjahn_agent_inspector_VMInspector
 * Method:    getAllClassLoadersOfType
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_net_mjahn_agent_inspector_VMInspector_getAllClassLoadersOfType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_mjahn_agent_inspector_VMInspector
 * Method:    getAllClassLoaders
 * Signature: ()[Ljava/lang/ClassLoader;
 */
JNIEXPORT jobjectArray JNICALL Java_net_mjahn_agent_inspector_VMInspector_getAllClassLoaders
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
